### ISSUE TITLE
NPE shows up when initializing component

### ISSUE THREAD

**Issue by LouisPennachio** [DevLight-Mobile-Agency/ArcProgressStackView#22]
I am using ArcProgressiveStackView in two different fragments. In the first one everything works fine, but in the second one I get this stacktrace when my view is initialized : 

> 12-18 11:04:09.093 4184-4184 W/System.err: java.lang.NullPointerException
12-18 11:04:09.093 4184-4184 W/System.err:     at android.graphics.Typeface.nativeCreateFromAsset(Native Method)
12-18 11:04:09.093 4184-4184 W/System.err:     at android.graphics.Typeface.createFromAsset(Typeface.java:149)
12-18 11:04:09.093 4184-4184 W/System.err:     at devlight.io.library.ArcProgressStackView.setTypeface(ArcProgressStackView.java:594)
12-18 11:04:09.093 4184-4184 W/System.err:     at devlight.io.library.ArcProgressStackView.<init>(ArcProgressStackView.java:212)
12-18 11:04:09.093 4184-4184 W/System.err:     at devlight.io.library.ArcProgressStackView.<init>(ArcProgressStackView.java:179)
12-18 11:04:09.093 4184-4184 W/System.err:     at java.lang.reflect.Constructor.constructNative(Native Method)
12-18 11:04:09.093 4184-4184 W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
12-18 11:04:09.093 4184-4184 W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:595)
12-18 11:04:09.093 4184-4184 W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697)
12-18 11:04:09.093 4184-4184 W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:756)
12-18 11:04:09.093 4184-4184 W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
12-18 11:04:09.093 4184-4184 W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
12-18 11:04:09.093 4184-4184 W/System.err:     at <...>.MyFragment.onCreateView(MyFragment.java:37)

This is not causing any issues for me, but I am not using the text labels that may be impacted by this error. My fonts are located under res/font.

**Comment by LouisPennachio** [comment]
Problem solved after I specified a typeface in my xml : 

`app:apsv_typeface="fonts/lato_black.ttf"`

I had to create a dedicated folder for my fonts under **assets/fonts** because I could not find a way to use the existing fonts I had in my folder **res/font**
